### ISSUE TITLE
Warning on OrderedDefaultRouter's APIRootView attribute

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot-app-data-validation-engine#162]
### Environment
* Python version: 3.11
* Nautobot version: 2.2.2
* nautobot-data-validation-engine version: 3.1.1

### Expected Behavior
No warning messages

### Observed Behavior
When the instance starts, or a nautobot-server command issued, a warning is shown:
```
$ nautobot-server health_check
15:54:45.342 WARNING nautobot.core.api.routers :
  Something has changed an OrderedDefaultRouter's APIRootView attribute to a custom class. Please verify that class DataValidationEngineRootView implements appropriate authentication controls.
DatabaseBackend          ... working
DefaultFileStorageHealthCheck ... working
MigrationsBackend        ... working
RedisBackend             ... working
```

### Steps to Reproduce
1. Install this app
2. Run `nautobot-server health_check`

### Security

Does the issue pointed by this error message have a security impact / are this app endpoints accessible without authentication?

**Comment by u1735067** [comment]
Thank you ; I don't know if the branch supporting Nautobot LTM/1.6 is maintained, but versions from 1.6.16 are affected too.

**Comment by glennmatthews** [comment]
The security implication is minimal - without the fix, unauthenticated users can access the "browsable API" view at `/api/plugins/nautobot-data-validation-engine/`, but they still can't access any of the actual operational API endpoints underneath it.
